### ISSUE TITLE
Let ElasticSearch handle ids

### ISSUE THREAD

**Issue by awest1339** [awest1339/multiscanner#27]
* https://github.com/awest1339/multiscanner/blob/celery/storage/elasticsearch_storage.py#L475
* Should let ES handle the ID assignment here because it will prevent ID collisions
* Also, consider use of index vs create

**Comment by clenk** [comment]
Interestingly, this forces us to use `index()` instead of `create()` because `id` is optional for `index()` but required for `create()`.

Also, this issue is fixed in my latest PR.

**Comment by clenk** [comment]
Fixed by 047fa86.

**Comment by clenk** [comment]
This can be closed.
